// A1 → A2 → early B1 curriculum review, aligned to common beginner-course coverage.
const section=(title,intro,points,examples,note)=>({title,intro,points,examples,note});
const setLesson=(id,{title,desc,focus,rules,sections,qs})=>{const c=COURSE.find(x=>x.id===id);Object.assign(c,{title:title||c.title,desc:desc||c.desc,focus:focus||c.focus,rules:rules||c.rules,sections:sections||c.sections,qs:qs||c.qs});return c};

const beThereHave={id:'be-there-have',title:'be、there be 与 have got',desc:'表达身份、状态、位置、存在和拥有。',level:'A1 核心',focus:'最常用的三种基础结构',rules:['be 连接身份、状态和地点。','there is / are 表示某处存在某物。','have / have got 表示拥有，注意各自的疑问和否定形式。'],examples:[['I am a student.','身份'],['There are two cafés nearby.','存在'],['She has got a bike.','拥有']],words:[['identity','n. 身份'],['location','n. 位置'],['exist','v. 存在'],['possession','n. 拥有']],sections:[
 section('1. be 表示“是、处于、在”','be 会根据主语和时间变化。',['现在：I am；he / she / it is；you / we / they are。','过去：I / he / she / it was；you / we / they were。','be 后可接名词、形容词或地点短语。'],[['She is a doctor.','名词说明身份。'],['They are tired.','形容词说明状态。'],['The keys are on the table.','介词短语说明地点。']]),
 section('2. there is / there are','there be 用来第一次介绍“某处有什么”。',['单数或不可数名词用 there is；复数名词用 there are。','否定在 be 后加 not；疑问把 be 放到 there 前。','be 与后面第一个名词保持单复数一致。'],[['There is some milk in the fridge.','milk 不可数，用 is。'],['Are there any shops nearby?','疑问句：Are + there。']]),
 section('3. have 与 have got','两者都可表示拥有，have got 在口语中很常见。',['I / you / we / they have；he / she / it has。','普通 have 的疑问常用 do / does：Do you have...?','have got 的疑问直接提前 have / has：Have you got...?','不要混合两套结构。'],[['She has a car. → Does she have a car?','普通 have 使用 does。'],['She has got a car. → Has she got a car?','have got 直接提前 has。']], 'Does she has got...? 是把两套结构混在一起，应避免。')
],qs:[q('I ___ from Australia.','am|is|are|be',0,'主语 I 与 am 搭配。','be'),q('My parents ___ at home.','is|am|are|be',2,'复数主语 parents 使用 are。','be'),q('There ___ a book on the desk.','are|is|have|be',1,'a book 是单数，用 there is。','there be'),q('There ___ two windows in the room.','is|are|has|be',1,'two windows 是复数，用 there are。','there be'),q('___ there any milk?','Are|Is|Do|Does',1,'milk 不可数，使用 Is there...?','there be'),q('She ___ a new laptop.','have|has|is|are',1,'she 的 have 形式是 has。','have'),q('___ you have a passport?','Are|Do|Have got|Does',1,'普通 have 的疑问使用 Do you have...?','have'),q('Has he ___ a brother?','have|got|gets|having',1,'have got 的疑问结构是 Has he got...?','have got'),q('选择正确句子。','Does she has a car?|Does she have a car?|Has she have a car?|She have a car.',1,'does 后主要动词使用原形 have。','have'),q('The children ___ very quiet yesterday.','are|was|were|be',2,'复数主语的 be 过去式是 were。','be过去式')]};

const pronouns={id:'pronouns',title:'代词、所有格与反身代词',desc:'正确使用 I/me、my/mine、myself 等常用形式。',level:'A1 核心',focus:'同一个人的不同代词形式',rules:['主格作主语，宾格作动词或介词的宾语。','形容词性物主代词后必须接名词；名词性物主代词可独立使用。','反身代词表示动作回到主语自身，或用于强调。'],examples:[['She called me.','She 主格；me 宾格'],['This is my bag. That one is mine.','my + 名词；mine 独立'],['He taught himself.','反身代词']],words:[['pronoun','n. 代词'],['possessive','adj. 所有格的'],['reflexive','adj. 反身的'],['belong','v. 属于']],sections:[
 section('1. 主格与宾格','位置决定形式，不由中文意思决定。',['主格：I, you, he, she, it, we, they，通常放在谓语前。','宾格：me, you, him, her, it, us, them，放在动词或介词后。'],[['They invited us.','They 作主语；us 作 invited 的宾语。'],['Come with me.','介词 with 后用宾格 me。']]),
 section('2. my 还是 mine','先看后面有没有名词。',['my, your, his, her, its, our, their 后接名词。','mine, yours, his, hers, ours, theirs 后面不再接名词。','its 表示“它的”；it’s 是 it is 或 it has 的缩写。'],[['This is our room.','our 后接 room。'],['This room is ours.','ours 独立使用。']]),
 section('3. 反身代词','主语和宾语指同一个人时使用反身代词。',['myself, yourself, himself, herself, itself, ourselves, yourselves, themselves。','by myself 表示独自；I did it myself 用于强调“亲自”。'],[['She looked at herself in the mirror.','she 和 herself 是同一人。'],['We made the cake ourselves.','ourselves 强调亲自完成。']])
],qs:[q('___ am ready.','Me|I|My|Mine',1,'句子主语使用主格 I。','主格'),q('Can you help ___?','I|my|me|mine',2,'动词 help 后使用宾格 me。','宾格'),q('She spoke to ___.','he|his|him|himself is',2,'介词 to 后使用宾格 him。','宾格'),q('This is ___ phone.','me|mine|my|I',2,'phone 前使用形容词性物主代词 my。','物主代词'),q('That blue car is ___.','their|theirs|them|they',1,'后面没有名词，使用 theirs。','物主代词'),q('We enjoyed ___ at the party.','us|our|ours|ourselves',3,'enjoy oneself 表示玩得开心。','反身代词'),q('He fixed the bike by ___.','him|his|himself|he',2,'by himself 表示独自。','反身代词'),q('The cat is washing ___ paws.','it’s|its|it|itself',1,'its 是形容词性物主代词，修饰 paws。','its'),q('选择正确句子。','This book is her.|This book is hers.|This is hers book.|This book is she.',1,'hers 可独立作表语。','物主代词'),q('Anna and I made dinner ___.','ourselves|themselves|myself|us',0,'Anna and I 对应 ourselves。','反身代词')]};

const presentContinuous={id:'present-cont',title:'现在进行时',desc:'描述此刻、当前阶段和已经安排好的近期活动。',level:'A1–A2',focus:'be + 动词-ing',rules:['结构是 am / is / are + 动词-ing。','常表示此刻或当前阶段正在发生的动作。','状态动词通常使用一般现在时，不用进行时。'],examples:[['She is talking now.','此刻'],['I am reading a useful book this week.','当前阶段'],['I know the answer.','状态动词']],words:[['temporary','adj. 暂时的'],['currently','adv. 当前'],['happen','v. 发生'],['arrangement','n. 安排']],sections:[
 section('1. 构成与拼写','be 承担人称变化，主要动词变成 -ing。',['一般加 -ing：work → working。','以不发音 e 结尾通常去 e：make → making。','重读闭音节可双写末字母：run → running。','ie 变 y：lie → lying。'],[['I am waiting.','I 使用 am。'],['They are running.','they 使用 are；run 双写 n。']]),
 section('2. 什么时候使用','进行时关注“正在展开”的过程。',['now、right now、at the moment 常提示此刻。','today、this week 可表示暂时的当前阶段。','已确定的近期个人安排也可使用现在进行时。'],[['We are staying with friends this week.','暂时安排。'],['I am meeting Mia tomorrow.','已经约好的近期安排。']]),
 section('3. 与一般现在时对比','习惯用一般现在时，眼前或暂时动作使用进行时。',['She works at a bank. 表示长期工作。','She is working from home today. 表示今天的临时情况。','know、like、want、believe 等状态动词通常不用进行时。'],[['I like this song.','不是 I am liking。'],['What do you do? / What are you doing?','职业或习惯 / 此刻正在做什么。']])
],qs:[q('Look! It ___.','rains|is raining|rain|rained',1,'Look 提示此刻正在发生。','现在进行时'),q('I ___ dinner right now.','cook|am cooking|cooked|cooks',1,'right now 使用现在进行时。','现在进行时'),q('She ___ a red coat today.','wears always|is wearing|wear|wore every day',1,'today 的临时状态用现在进行时。','暂时动作'),q('They are ___ in the park.','run|runing|running|ran',2,'run 变 running 时双写 n。','ing拼写'),q('He is ___ a cake.','makeing|making|made|makes',1,'make 去 e 加 ing。','ing拼写'),q('I ___ the answer.','am knowing|know|knowing|knows',1,'know 是状态动词，通常不用进行时。','状态动词'),q('She usually drives, but today she ___ the bus.','takes|is taking|take|took now',1,'today 与通常习惯对比，使用进行时。','时态对比'),q('___ they waiting outside?','Do|Are|Is|Does',1,'进行时疑问句把 are 提前。','疑问句'),q('We ___ Tom tomorrow evening; the table is booked.','meet|are meeting|met|meets',1,'已安排的近期活动可用现在进行时。','未来安排'),q('选择正确句子。','I am want a coffee.|I wanting a coffee.|I want a coffee.|I do wanting a coffee.',2,'want 是状态动词，使用一般现在时。','状态动词')]};

const prepositions={id:'prepositions',title:'时间、地点与方向介词',desc:'掌握日常表达中最高频的 in、on、at 和移动介词。',level:'A1–A2',focus:'介词与时间、空间关系',rules:['at 常指具体点，on 常指表面或具体日期，in 常指范围内部。','时间表达中 at + 时刻，on + 日期/星期，in + 月份/年份/较长时期。','方向介词描述移动，地点介词描述位置。'],examples:[['at 7 o’clock','具体时刻'],['on Monday','具体日期'],['in July','月份']],words:[['preposition','n. 介词'],['location','n. 位置'],['direction','n. 方向'],['movement','n. 移动']],sections:[
 section('1. 时间：at / on / in','从最具体的点到更大的时间范围。',['at + 时刻：at 8:30；也用于 at night。','on + 星期或日期：on Friday, on 12 May。','in + 月、年、季节或较长时期：in June, in 2026。','last、next、this、every 前通常不加介词。'],[['The class starts at nine.','具体时刻。'],['We met on Monday in April.','星期用 on，月份用 in。']]),
 section('2. 地点：at / on / in','思考“点、表面、内部范围”。',['at 表示一个地点点位：at the station。','on 表示在表面上：on the wall。','in 表示在内部或较大区域：in the room, in Australia。'],[['She is waiting at the bus stop.','把车站看作一个点。'],['There is a picture on the wall.','接触墙面。']]),
 section('3. 位置与移动','位置和方向不要混淆。',['位置：under, above, behind, between, next to, opposite。','移动：to, into, out of, across, through, along, past。','into 强调进入内部；in 表示已经在内部。'],[['He walked into the room.','从外面进入。'],['He is in the room.','现在的位置。']])
],qs:[q('The lesson starts ___ 9 a.m.','in|on|at|to',2,'具体时刻使用 at。','时间介词'),q('We have class ___ Monday.','at|on|in|by',1,'星期前使用 on。','时间介词'),q('She was born ___ 2001.','at|on|in|from',2,'年份前使用 in。','时间介词'),q('The keys are ___ the table.','on|at time|into|to',0,'在桌面上使用 on。','地点介词'),q('He lives ___ Canada.','at|on|in|to',2,'国家范围内部使用 in。','地点介词'),q('Meet me ___ the station.','in year|at|on Monday|into',1,'把车站看作会面点时用 at。','地点介词'),q('The cat is ___ the chair.','under|across|through|to',0,'under 表示在下方。','位置介词'),q('She walked ___ the room and sat down.','in|into|at|on',1,'有进入动作，使用 into。','方向介词'),q('We drove ___ the bridge.','across|under of|between to|in',0,'across 表示从一边到另一边。','方向介词'),q('选择正确表达。','on next Monday|in yesterday|at 2025|next Monday',3,'last、next、this、every 前通常不加介词。','零介词')]};

const pastContinuous={id:'past-cont',title:'过去进行时',desc:'描述过去某个时刻正在发生的背景动作。',level:'A2',focus:'was / were + 动词-ing',rules:['结构是 was / were + 动词-ing。','长背景动作常与一般过去时的短事件配合。','while 常连接持续动作，when 常引入发生的事件。'],examples:[['I was reading at eight.','过去某时正在进行'],['I was reading when she called.','背景＋事件'],['While I was cooking, he was setting the table.','两个同时动作']],words:[['background','n. 背景'],['interrupt','v. 打断'],['while','conj. 当……时'],['suddenly','adv. 突然']],sections:[
 section('1. 构成与用途','把镜头放在过去某个时刻的动作过程上。',['I / he / she / it 用 was；you / we / they 用 were。','否定在 was / were 后加 not。','疑问把 was / were 放在主语前。'],[['At 10 p.m., I was sleeping.','十点时动作正在进行。'],['Were they waiting?','把 were 提前。']]),
 section('2. 背景动作与短事件','背景动作使用过去进行时，突然发生或完成的事件用一般过去时。',['I was walking home when it started to rain.','when 后不一定永远用一般过去时，要看动作是过程还是事件。'],[['The phone rang while I was having a shower.','洗澡是背景，电话响是短事件。']]),
 section('3. 两个同时进行的动作','两个动作在过去同时持续时，都可以使用过去进行时。',['while 比 when 更强调两件事同时持续。'],[['While Mia was studying, Leo was watching TV.','两个动作同时进行。']])
],qs:[q('At eight last night, I ___.','was studying|studied now|am studying|study',0,'过去具体时刻正在发生，用过去进行时。','过去进行时'),q('They ___ dinner when I arrived.','had|were having|are having|have',1,'吃饭是背景动作。','背景动作'),q('The phone ___ while I was sleeping.','rang|was ringing once|rings|ring',0,'电话响是发生并完成的短事件。','时态对比'),q('While we ___, it started to snow.','walked always|were walking|are walking|have walked',1,'while 引出持续背景动作。','while'),q('She was ___ when the lights went out.','read|reading|reads|to read',1,'was 后接动词-ing。','结构'),q('___ you working at six?','Did|Were|Was|Are',1,'you 的过去进行时疑问使用 Were。','疑问句'),q('He ___ not listening.','did|was|had|is yesterday',1,'过去进行时否定为 was not listening。','否定句'),q('While I was cooking, Sam ___.','was washing the dishes|washed every day|is washing|wash',0,'两个同时持续的动作都可用过去进行时。','同时动作'),q('选择正确句子。','I was walk home when it rained.|I was walking home when it started to rain.|I walked home while it was start.|I am walking yesterday.',1,'背景使用 was walking，短事件使用 started。','时态对比'),q('What ___ at 9 p.m. yesterday?','did you doing|were you doing|are you do|you were do',1,'过去进行时特殊疑问：What were you doing...?','疑问句')]};

const relative={id:'relative',title:'定语从句与间接疑问句',desc:'用 who、which、that 描述名词，并使用礼貌的间接提问。',level:'A2–B1 衔接',focus:'扩展名词与嵌入问题',rules:['定语从句紧跟被修饰的名词。','who 指人，which 指物，that 常可指人或物。','间接疑问句使用陈述语序。'],examples:[['The woman who called is my aunt.','who 指人'],['The book that I bought is useful.','that 指物'],['Do you know where he lives?','陈述语序']],words:[['relative clause','n. 定语从句'],['describe','v. 描述'],['indirect','adj. 间接的'],['polite','adj. 礼貌的']],sections:[
 section('1. 定语从句做什么','它像一段较长的形容词，放在名词后说明“哪一个”。',['先行词是人常用 who / that。','先行词是物常用 which / that。','whose 表示所属；where 表示地点。'],[['The student who sits there is new.','who 从句说明是哪位学生。'],['This is the café where we met.','where 从句说明是哪家咖啡馆。']]),
 section('2. 关系词作主语或宾语','看关系词在从句中缺什么成分。',['作主语时不能省略：The man who lives next door。','作宾语时常可省略：The book (that) I bought。','逗号补充信息的非限制性从句通常不用 that。'],[['The film that won the award...','that 作 won 的主语，不能省略。'],['The film (that) we watched...','that 作 watched 的宾语，可以省略。']]),
 section('3. 间接疑问句','礼貌提问或把问题放进另一个句子时，内部使用陈述语序。',['直接问句：Where does she live?','间接问句：Could you tell me where she lives?','一般疑问句嵌入时使用 if / whether。'],[['Do you know if the shop is open?','内部不是 is the shop open。'],['Can you tell me what time it starts?','内部使用 it starts。']])
],qs:[q('The woman ___ lives next door is a doctor.','which|who|where|whose',1,'先行词是人，关系词在从句中作主语，用 who。','who'),q('This is the phone ___ I bought.','who|where|that|whose',2,'先行词是物，that 可作宾语。','that'),q('The girl ___ bag is red is my sister.','who|whose|which|where',1,'whose 表示所属关系。','whose'),q('That is the town ___ I grew up.','who|which person|where|whose',2,'先行词是地点，使用 where。','where'),q('关系词可以省略的是？','The man who called|The book that I read|The dog which barked|The student who won',1,'that 作 read 的宾语，可以省略。','关系词省略'),q('Could you tell me where she ___?','does live|lives|live|is live',1,'间接疑问句使用陈述语序。','间接疑问句'),q('Do you know ___ the bank is open?','what|if|does|that is',1,'嵌入一般疑问句使用 if / whether。','if-whether'),q('选择正确句子。','Can you tell me where is the station?|Can you tell me where the station is?|Can you tell me where does the station be?|Can you tell where is station?',1,'间接疑问句内部使用陈述语序。','间接疑问句'),q('The film ___ won the award was excellent.','that|where|whose|it',0,'that 在从句中作主语，不能省略。','that'),q('My brother, ___ lives in Perth, is visiting.','that|who|where|what',1,'逗号后的补充性定语从句指人，用 who。','非限制性从句')]};

// Make new chapters available before applying cross-chapter additions below.
[beThereHave,pronouns,presentContinuous,prepositions,pastContinuous,relative].forEach(c=>{if(!COURSE.some(x=>x.id===c.id))COURSE.push(c)});

// Split previously combined tense chapters and deepen every retained lesson.
setLesson('nouns',{sections:[section('1. 可数与不可数','先判断名词能否直接计数。',['单数可数名词前通常需要 a/an、the、this、my 等限定词。','不可数名词通常没有复数，也不用 a/an。','advice、information、furniture、homework 是常见不可数名词。'],[['a piece of advice','用量词表达一条建议。'],['some information','information 不加 s。']]),section('2. 冠词 a/an/the','a/an 是泛指一个，the 指双方能确定的对象。',['a/an 的选择看读音，不只看字母。','第一次提及常用 a/an，再次提及可用 the。','独一事物、最高级前常用 the。'],[['I saw a dog. The dog was friendly.','先泛指，再特指。']]),section('3. 数量词','可数性决定数量词。',['many / a few / few + 可数复数。','much / a little / little + 不可数。','some / any / a lot of 可与两类名词搭配。'],[['There are a few chairs.','有几把，偏肯定。'],['There is little time.','几乎没时间，偏否定。']]) ]});

setLesson('present',{title:'一般现在时与频率副词',desc:'表达日常习惯、事实、长期状态和固定安排。',focus:'原形 / 第三人称单数',rules:['一般现在时表示习惯、事实和长期状态。','he / she / it 后的动词通常加 -s 或 -es。','频率副词放在实义动词前、be 动词后。'],sections:[section('1. 什么时候使用','一般现在时不等于“此刻”，它关注规律和状态。',['习惯：I walk to work every day。','事实：Water boils at 100°C。','长期状态：She lives in Sydney。','时刻表：The train leaves at eight。'],[['I know the answer.','know 是状态动词。']]),section('2. 第三人称单数','he、she、it 是最常见易错点。',['大多数动词加 -s。','-s, -sh, -ch, -x, -o 结尾常加 -es。','辅音字母 + y 变 y 为 i 加 -es。','have → has；do → does；go → goes。'],[['She watches TV.','watch → watches。'],['He studies English.','study → studies。']]),section('3. 频率副词','位置通常由谓语类型决定。',['always, usually, often, sometimes, rarely, never。','实义动词前：She often walks。','be 后：She is often late。'],[['How often do you exercise?','询问频率。']])],qs:[q('She ___ to work every day.','walk|walks|is walking now|walked',1,'日常习惯用一般现在时，she 后加 s。','第三人称'),q('Water ___ at 100°C.','boil|boils|is boiling always|boiled',1,'客观事实使用一般现在时。','事实'),q('He ___ TV every evening.','watch|watches|watchs|is watch',1,'watch 以 ch 结尾，加 es。','第三人称'),q('Mia ___ English at school.','study|studys|studies|studying',2,'辅音 + y 变 y 为 i 加 es。','第三人称'),q('I ___ the answer.','am knowing|know|knows|knowing',1,'know 是状态动词。','状态动词'),q('She is ___ late.','often|often is|late often before is|does often',0,'频率副词放在 be 后。','频率副词'),q('They ___ eat breakfast at home.','usually|are usually|usual|are usual eat',0,'频率副词放在实义动词 eat 前。','频率副词'),q('The train ___ at 7:15 tomorrow.','leave|leaves|is leave|will leaves',1,'固定时刻表可用一般现在时。','时刻表'),q('选择正确句子。','He don’t like tea.|He doesn’t likes tea.|He doesn’t like tea.|He not likes tea.',2,'doesn’t 后使用动词原形。','否定句'),q('How often ___ she exercise?','do|does|is|has',1,'she 的一般现在时疑问使用 does。','疑问句')]});

setLesson('wh',{sections:[section('1. 选择疑问词','先确定想知道的信息类型。',['who 人；what 事物；which 有限选择；whose 所属。','where 地点；when 时间；why 原因；how 方式或状态。'],[['Why are you late? — Because...','why 问原因。']]),section('2. how 组合','how 与其他词组合形成高频问题。',['how many + 可数复数；how much + 不可数或价格。','how often 频率；how long 时长；how far 距离；how old 年龄。'],[['How long have you lived here?','询问持续多久。']]),section('3. 对主语还是宾语提问','这是 who 问句最关键的区别。',['Who called you? who 就是主语，不加 did。','Who did you call? who 是宾语，需要 did。'],[['Who broke the window?','不知道动作执行者，直接用 who + 谓语。']]) ]});

setLesson('adjadv',{sections:[section('1. 形容词与副词','看它修饰谁。',['形容词修饰名词，或放在系动词后。','副词修饰动词、形容词、副词或整句。','friendly、lovely 虽以 -ly 结尾，通常是形容词。'],[['She is a careful driver.','careful 修饰 driver。'],['She drives carefully.','carefully 修饰 drives。']]),section('2. -ed 与 -ing','区分感受者和引发感受的事物。',['-ed 常描述人的感受：I am bored。','-ing 常描述令人产生感受的事物：The class is boring。'],[['The result was surprising. We were surprised.','事情令人惊讶；人感到惊讶。']]),section('3. 比较级与最高级','比较两者用比较级，三者或范围内最高用最高级。',['短词常加 -er/-est；长词常用 more/most。','good → better → best；bad → worse → worst。','比较级后常用 than；最高级前通常有 the。'],[['This book is more useful than that one.','长形容词用 more。']]) ]});

setLesson('past',{title:'一般过去时',desc:'表达过去发生并结束的动作和状态。',focus:'过去式与 did',rules:['明确结束的过去事件使用一般过去时。','规则动词加 -ed，不规则动词需要记忆。','否定和疑问使用 did，主要动词恢复原形。'],sections:[section('1. 过去式','时间已经结束是核心。',['规则动词一般加 -ed。','常见不规则：go→went, see→saw, buy→bought, take→took。','be 的过去式是 was / were。'],[['We visited Melbourne last year.','last year 已结束。']]),section('2. 否定与疑问','did 承担过去时。',['否定：did not / didn’t + 原形。','疑问：Did + 主语 + 原形？','be 句直接使用 was / were，不加 did。'],[['Did she go?','不是 Did she went。'],['Was he tired?','be 直接提前。']]),section('3. 叙述连续事件','讲故事时，一连串完成动作都可用一般过去时。',['first、then、after that、finally 帮助组织顺序。'],[['She opened the door, walked in and sat down.','三个连续完成动作。']])],qs:[q('We ___ to the beach last Sunday.','go|went|gone|were go',1,'last Sunday 用一般过去时。','过去式'),q('Did you ___ the email?','received|receive|receiving|receives',1,'did 后用原形。','动词原形'),q('She ___ not call me.','does|did|was|is',1,'过去时否定使用 did not。','否定句'),q('___ he tired after work?','Did|Was|Does|Is yesterday',1,'tired 前用 be，过去式 he was。','be过去式'),q('buy 的过去式是？','buyed|bought|brought|buying',1,'buy 的不规则过去式是 bought。','不规则动词'),q('go 的过去式是？','gone|went|goed|going',1,'went 是过去式；gone 是过去分词。','不规则动词'),q('They ___ home, opened the door and sat down.','returned|return|were return|have return',0,'连续完成的过去动作使用一般过去时。','叙事'),q('选择正确句子。','Did she went home?|Did she go home?|She didn’t went home.|Was she go home?',1,'did 后使用原形 go。','动词原形'),q('I ___ him yesterday.','see|seen|saw|have seen',2,'yesterday 是明确过去时间，see 的过去式是 saw。','过去式'),q('We ___ at home last night.','are|was|were|be',2,'we 的 be 过去式是 were。','be过去式')]});

setLesson('future',{sections:[section('1. will','用于即时决定、承诺和没有明显证据的一般预测。',['结构：will + 动词原形。','否定：will not / won’t。','疑问：Will + 主语 + 原形？'],[['The phone is ringing. I’ll answer it.','即时决定。']]),section('2. be going to','用于已有意图或根据眼前证据作预测。',['be 随主语变化；going to 后用原形。'],[['Look at those clouds. It is going to rain.','有眼前证据。']]),section('3. 已安排与时间表','未来不只有 will。',['现在进行时表示已安排的个人活动。','一般现在时表示固定日程、时刻表。','when / if 时间条件从句中常用一般现在时代替 will。'],[['I’m meeting Jo tomorrow.','已约好。'],['I’ll call when I arrive.','不是 when I will arrive。']]) ]});

setLesson('modals',{sections:[section('1. 基本结构','情态动词后直接接原形。',['没有第三人称 -s。','否定直接加 not。','疑问把情态动词放到主语前。'],[['She can swim. / Can she swim?','can 不变化。']]),section('2. 常用功能','一个情态动词可有多个语用功能。',['can/could：能力、请求、许可。','should：建议；must/have to：义务。','may/might：可能性。'],[['You should rest.','建议。']]),section('3. 禁止、不必与推测','相似形式可能意义完全不同。',['mustn’t = 禁止；don’t have to = 不必。','must be = 很可能；might be = 可能；can’t be = 不可能。'],[['You mustn’t park here.','禁止停车。'],['You don’t have to come early.','没有必要早来。']]) ]});

setLesson('perfect',{sections:[section('1. 构成与过去分词','have / has + 过去分词。',['规则过去分词常与过去式相同。','常见不规则：go→gone, see→seen, write→written。'],[['She has finished.','she 使用 has。']]),section('2. 三种常见用途','完成时把过去与现在连接起来。',['当前结果：I have lost my key。','人生经历：Have you ever been...?','持续到现在：We have lived here for five years。'],[['She has just arrived.','刚到，现在已经在这里。']]),section('3. 与一般过去时对比','看时间是否是已结束的明确过去。',['yesterday、last year、in 2020 通常用一般过去时。','ever、never、already、yet、just 常与现在完成时搭配。','since + 起点；for + 时长。'],[['I saw him yesterday.','明确过去时间。'],['I have seen that film twice.','经历，没有指定结束时间。']]) ]});

setLesson('nonfinite',{sections:[section('1. to do','不定式常表示计划、意愿和目的。',['want, hope, decide, plan + to do。','too / enough + to do。','动词不定式可表示目的。'],[['I went out to buy milk.','目的。']]),section('2. doing','动名词把动作当成一件事。',['enjoy, avoid, finish, mind + doing。','介词后使用 doing。','doing 可作句子主语。'],[['Reading helps me relax.','Reading 作主语。']]),section('3. 形式改变，意义改变','少数动词后两种形式意义不同。',['stop doing 停止正在做；stop to do 停下来去做。','remember doing 记得做过；remember to do 记得要做。','try doing 尝试方法；try to do 努力完成。'],[['I stopped smoking. / I stopped to smoke.','停止吸烟 / 停下来去吸烟。']]) ]});

setLesson('clauses',{title:'连接词与基础条件句',desc:'用 and、but、because、although、if 等连接完整意思。',focus:'从简单句到复合句',rules:['and、but、or、so 连接并列信息。','because、when、although 引导原因、时间和让步从句。','零条件句讲规律，第一条件句讲真实可能的未来。'],sections:[section('1. 并列连接词','选择词取决于逻辑关系。',['and 添加；but 转折；or 选择；so 结果。','不要在同一结构中重复 because...so 或 although...but。'],[['It was raining, so we stayed home.','原因导致结果。']]),section('2. 常用状语从句','从句为主句补充时间、原因或让步。',['because + 完整句；because of + 名词短语。','although 表示尽管；when/while/as soon as 表示时间。'],[['Although it was late, we kept working.','让步关系。']]),section('3. 零条件与第一条件','if 从句中通常不用 will。',['零条件：If + 现在时，主句现在时，表示规律。','第一条件：If + 现在时，主句 will + 原形，表示真实可能。'],[['If you heat ice, it melts.','规律。'],['If it rains, we will stay home.','未来可能。']])],qs:[q('I stayed home ___ it was raining.','because|but|so|because of',0,'because 后接完整句。','原因'),q('It was raining, ___ we stayed home.','because|so|although|or',1,'后半句是结果，用 so。','结果'),q('___ he was tired, he kept working.','Although|Because of|So|And',0,'前后是让步关系。','让步'),q('We can walk ___ take the bus.','because|or|so|although',1,'两种选择使用 or。','选择'),q('If you heat water to 100°C, it ___.','will boiled|boils|boil|is boil',1,'规律使用零条件句的现在时。','零条件句'),q('If it rains tomorrow, we ___ home.','stay yesterday|will stay|will stayed|stayed',1,'第一条件句主句使用 will + 原形。','第一条件句'),q('I’ll call you when I ___.','will arrive|arrive|arrived tomorrow|am arrive',1,'时间从句中用一般现在时代替 will。','时间从句'),q('选择正确句子。','Because it rained, so we stayed home.|Because it rained, we stayed home.|Although it rained, but we went out.|Because of it rained, we stayed home.',1,'because 不与 so 重复。','连词'),q('She left early ___ she was feeling ill.','because|although|but|or',0,'解释原因使用 because。','原因'),q('___ you finish, please turn off the computer.','As soon as|Because of|Despite|So',0,'as soon as 表示一完成就。','时间从句')]});

setLesson('passive',{sections:[section('1. 为什么使用被动','焦点是动作承受者，而不是执行者。',['执行者未知、不重要或显而易见时常用被动。','需要强调执行者时使用 by。'],[['My phone was stolen.','不知道或不强调小偷是谁。']]),section('2. 构成','be 承担时态，主要动词使用过去分词。',['现在：am/is/are + done。','过去：was/were + done。','将来：will be + done。','完成：has/have been + done。'],[['English is spoken here.','一般现在时被动。']]),section('3. 主动转被动','先找主动句的宾语。',['宾语移到主语位置。','按新主语和原时态选择 be。','主要动词改为过去分词。'],[['They built the bridge. → The bridge was built.','bridge 从宾语变主语。']]) ]});

COURSE.find(c=>c.id==='nouns').sections.push(section('4. the 与零冠词','有些常见表达不需要冠词。',['语言、学科、运动和泛指复数通常不用冠词：speak English, play tennis, Dogs are friendly。','表示日常功能时常说 go to school / be at work / go home。','大多数国家和城市不用 the；复数或联合名称常用 the，如 the United States。'],[['I go to school by bus.','school 表示日常功能，不加 the。'],['The school near my home is new.','指特定学校，使用 the。']]));
COURSE.find(c=>c.id==='pronouns').sections.push(section('4. 指示词与名词所有格','用距离、单复数和所有关系选择形式。',['this / these 指较近；that / those 指较远。','this / that 接单数；these / those 接复数。','单数名词通常加 ’s：Tom’s book；规则复数只加撇号：the students’ room。'],[['These shoes are mine.','these 对应复数 shoes。'],['This is Anna’s bag.','’s 表示包属于 Anna。']]));
COURSE.find(c=>c.id==='pronouns').qs.push(q('___ shoes over here are new.','This|That|These|It',2,'shoes 是复数且距离较近，使用 these。','指示词'),q('This is ___ desk.','Tom|Toms|Tom’s|Toms’',2,'单数名词 Tom 加 ’s 表示所有。','名词所有格'));
COURSE.find(c=>c.id==='modals').sections.push(section('4. 命令、请求与建议','日常交流中常用简洁结构推动行动。',['祈使句使用动词原形：Open the door。否定用 Don’t + 原形。','Let’s + 原形用于共同建议。','Can / Could you...? 用于请求；Could 通常更委婉。','Why don’t we...? 和 How about + doing...? 也可提出建议。'],[['Please sit down. / Don’t touch that.','肯定与否定祈使句。'],['Could you help me?','礼貌请求。']]));
COURSE.find(c=>c.id==='modals').qs.push(q('___ the window, please.','Opening|Open|To open|Opened',1,'祈使句使用动词原形。','祈使句'),q('Let’s ___ a break.','to take|taking|take|took',2,'Let’s 后使用动词原形。','建议'));
COURSE.find(c=>c.id==='past').sections.push(section('4. used to 表示过去习惯','用于过去经常发生、现在通常不再发生的状态或习惯。',['肯定：used to + 动词原形。','否定：didn’t use to + 原形。','疑问：Did ... use to + 原形？'],[['I used to walk to school.','过去常常步行，现在情况不同。'],['Did you use to live here?','did 后写 use，不写 used。']]));
COURSE.find(c=>c.id==='past').qs.push(q('I ___ play outside every day when I was a child.','use to|used to|was use to|using to',1,'过去习惯使用 used to + 原形。','used to'),q('Did she ___ live here?','used to|use to|using to|uses to',1,'did 后使用 use to。','used to'));

// Final progression: concrete A1 patterns first, then A2 tense contrasts, then early-B1 expansion.
const order=['skeleton','be-there-have','nouns','pronouns','present','questions','wh','present-cont','adjadv','prepositions','past','past-cont','future','modals','perfect','nonfinite','clauses','passive','relative'];
const added=[beThereHave,pronouns,presentContinuous,prepositions,pastContinuous,relative];
added.forEach(c=>{if(!COURSE.some(x=>x.id===c.id))COURSE.push(c)});
const phaseMap={skeleton:'阶段一 · A1 句子基础','be-there-have':'阶段一 · A1 句子基础',nouns:'阶段一 · A1 句子基础',pronouns:'阶段一 · A1 句子基础',present:'阶段二 · A1 日常表达',questions:'阶段二 · A1 日常表达',wh:'阶段二 · A1 日常表达','present-cont':'阶段二 · A1 日常表达',adjadv:'阶段三 · A1–A2 描述世界',prepositions:'阶段三 · A1–A2 描述世界',past:'阶段四 · A2 时间与经历','past-cont':'阶段四 · A2 时间与经历',future:'阶段四 · A2 时间与经历',modals:'阶段五 · A2 功能表达',perfect:'阶段五 · A2 功能表达',nonfinite:'阶段五 · A2 功能表达',clauses:'阶段六 · A2–B1 连接与扩展',passive:'阶段六 · A2–B1 连接与扩展',relative:'阶段六 · A2–B1 连接与扩展'};
const ordered=order.map(id=>COURSE.find(c=>c.id===id));
COURSE.splice(0,COURSE.length,...ordered);
COURSE.forEach((c,i)=>{c.no=String(i+1).padStart(2,'0');c.phase=phaseMap[c.id];if(!c.level||!c.level.match(/A\d/))c.level=i<8?'A1':i<16?'A2':'A2–B1'});
