const Explain=(()=>{
 const guides=[
  {match:/時|過去|現在|未來|完成|進行|used to|經歷|持續/,name:'時態判斷',steps:['先圈出時間詞或上下文時間點。','判斷動作是習慣、進行過程、完成結果還是已結束事件。','再依主詞選擇助動詞或動詞形式。'],pitfall:'不要只靠單一「提示詞」機械式地選擇時態；先確認動作與時間參照點的關係。'},
  {match:/疑問|do|does|did|簡短回答|否定|語序/,name:'疑問與否定',steps:['先找原句的完整動詞片語。','已有 be、情態助動詞或完成式 have 時直接移動它；否則一般時態使用 do。','出現 does 或 did 後，把主要動詞恢復原形。'],pitfall:'最常見錯誤是重複標記：Does she works 和 Did he went 都把時態標記了兩次。'},
  {match:/be|there be|have got/,name:'be 與基礎結構',steps:['確認表達的是身分、狀態、位置、存在還是擁有。','根據主詞和時間選擇 am/is/are/was/were 或 have/has。','否定和提問時保持同一套結構，不混用 do 與 have got。'],pitfall:'be 句不使用 do 提問；普通 have 與 have got 的提問方式不要混合。'},
  {match:/名詞|冠詞|可數|不可數|複數|數量|限定|所有格|零冠詞/,name:'名詞與限定詞',steps:['先判斷名詞是可數還是不可數。','如果是單數可數名詞，檢查前面是否有限定詞。','再根據泛指、特指和數量選擇冠詞或數量詞。'],pitfall:'information、advice、furniture 等常見詞在英文中不可數，不能直接加 a 或複數 -s。'},
  {match:/代名詞|主格|受格|所有格|反身|指示|its|whose/,name:'代名詞與指代',steps:['先判斷這個位置需要主詞、受詞還是所屬關係。','檢視後面是否還有名詞：有名詞用 my/your 等，沒有名詞用 mine/yours 等。','確認代名詞與所指對象在人稱和單複數上一致。'],pitfall:'my 後必須接名詞；mine 後不能再接名詞。its 是「它的」，it’s 是 it is/has。'},
  {match:/形容詞|副詞|比較|最高|ing-ed|連綴動詞|詞類/,name:'修飾與詞類',steps:['先找被修飾的詞。','修飾名詞或放在連綴動詞後通常用形容詞；修飾動作通常用副詞。','比較時確認是兩者比較還是範圍內最高。'],pitfall:'-ed 常描述感受者，-ing 常描述引發感受的事物；但判斷仍要結合句意。'},
  {match:/介系詞|地點|方向|距離|時間介系詞|零介系詞/,name:'介系詞關係',steps:['判斷表達的是時間、靜態位置還是移動方向。','時間從「點—具體日—較長範圍」判斷 at/on/in。','空間從「點—表面—內部」判斷 at/on/in，移動時再看 into/across/through。'],pitfall:'last、next、this、every 前通常不再加上時間介系詞。'},
  {match:/情態|建議|許可|能力|義務|禁止|不必|推測|祈使/,name:'情態與功能表達',steps:['先判斷說話人的目的：能力、許可、建議、義務還是推測。','選擇語氣強度合適的情態助動詞。','情態助動詞後使用原形動詞。'],pitfall:'mustn’t 表示禁止，don’t have to 表示沒有必要，兩者意義不同。'},
  {match:/不定詞|動名詞|doing|to do|目的|意義差異/,name:'動狀詞形式',steps:['檢視前面的動詞或介系詞決定基本搭配。','介系詞後通常使用 doing；want/plan/decide 等常接 to do。','遇到 stop、remember、try 時檢查形式變化是否改變意義。'],pitfall:'不要只記「某詞後接 doing/to do」，還要把會改變意義的搭配連同例句一起記。'},
  {match:/被動|語態|過去分詞|主動轉被動/,name:'被動語態',steps:['先確認主詞是動作執行者還是承受者。','依時態選擇 be 的形式。','主要動詞改為過去分詞；需要時再用 by 引出執行者。'],pitfall:'be 負責時態，過去分詞負責被動，二者缺一不可。'},
  {match:/子句|連接詞|條件|原因|結果|讓步|時間子句|who|that|where|if-whether|關係詞/,name:'子句與連接',steps:['先判斷兩個資訊之間的邏輯關係。','選擇連接詞並確認子句缺少什麼成分。','檢查子句語序；間接問句使用直述句語序。'],pitfall:'避免 because...so 和 although...but 雙重連接；if/when 的真實未來子句中通常不用 will。'},
  {match:/主詞|動詞片語|受詞|主詞補語|受詞補語|雙受詞|基本句型|完整句|詞類/,name:'句子成分',steps:['先找承擔時態的完整動詞片語。','動詞片語前通常是主詞。','再根據動詞類型判斷後面是受詞、主詞補語還是受詞補語。'],pitfall:'受詞補語描述或命名受詞；雙受詞分別表示「給誰」和「給什麼」。'}
 ];
 const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const guideFor=tag=>guides.find(g=>g.match.test(tag))||{name:'結構判斷',steps:['找出句子的主詞和完整動詞片語。','觀察題目要求與上下文線索。','用核心規則逐項排除不符合結構或意義的選項。'],pitfall:'不要只憑中文逐詞對應；英文形式要依句中位置、時態與固定搭配判斷。'};
 function layer(){let el=document.querySelector('#explain-layer');if(!el){el=document.createElement('div');el.id='explain-layer';el.className='explain-layer';el.innerHTML='<button class="explain-backdrop" aria-label="關閉詳細解析"></button><aside class="explain-sheet" role="dialog" aria-modal="true" aria-labelledby="explain-title"><button class="explain-close" aria-label="關閉">×</button><div id="explain-body"></div></aside>';document.body.appendChild(el);el.querySelector('.explain-backdrop').onclick=close;el.querySelector('.explain-close').onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape')close()})}return el}
 function open(html){const el=layer();el.querySelector('#explain-body').innerHTML=html;el.classList.add('open');document.body.classList.add('no-scroll');el.querySelector('.explain-close').focus();el.querySelectorAll('[data-reveal]').forEach(b=>b.onclick=()=>{const a=b.nextElementSibling;a.hidden=false;b.hidden=true})}
 function close(){document.querySelector('#explain-layer')?.classList.remove('open');document.body.classList.remove('no-scroll')}
 function mini(chapter,current){const q=chapter.qs.find(x=>x.text!==current?.text&&(x.tag===current?.tag||!current))||chapter.qs.find(x=>x.text!==current?.text);if(!q)return'';return `<section class="explain-block mini-check"><span>舉一反三</span><h3>${esc(q.text)}</h3><div class="mini-options">${q.options.map((o,i)=>`<i>${String.fromCharCode(65+i)}. ${esc(o)}</i>`).join('')}</div><button class="reveal-btn" data-reveal>檢視答案</button><div class="reveal-answer" hidden><b>${String.fromCharCode(65+q.a)}. ${esc(q.options[q.a])}</b><p>${esc(q.why)}</p></div></section>`}
 function knowledge(chapter,index){const s=chapter.sections[index],tag=s.title+' '+s.points.join(' '),g=guideFor(tag);open(`<div class="explain-kicker">文法重點詳解</div><h2 id="explain-title">${esc(s.title.replace(/^\d+\.\s*/,''))}</h2><p class="explain-lead">${esc(s.intro)}</p><section class="explain-block"><span>一步一步判斷</span><ol>${s.points.map(p=>`<li>${esc(p)}</li>`).join('')}</ol></section><section class="explain-block"><span>例句拆解</span>${s.examples.map(e=>`<div class="explain-example"><b>${esc(e[0])}</b><p>${esc(e[1])}</p></div>`).join('')}</section><section class="explain-warning"><b>常見誤區</b><p>${esc(s.note||g.pitfall)}</p></section>${mini(chapter)}`)}
 function question(chapter,q,chosen){const g=guideFor(q.tag),selected=Number.isInteger(chosen)?q.options[chosen]:'未作答',ok=chosen===q.a;const related=chapter.sections?.find(s=>(s.title+' '+s.points.join(' ')).includes(q.tag.replace(/時$|句$|式$/g,'')))||chapter.sections?.[0];open(`<div class="explain-kicker">題目詳解 · ${esc(q.tag)}</div><h2 id="explain-title">這一題要怎麼一步步判斷？</h2><div class="explain-question"><p>${esc(q.text)}</p><div><span class="${ok?'is-correct':'is-wrong'}">你的答案：${esc(selected)}</span><span class="is-correct">正確答案：${esc(q.options[q.a])}</span></div></div><section class="explain-block"><span>${esc(g.name)} · 判斷路徑</span><ol>${g.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol></section><section class="explain-block"><span>本題落點</span><h3>${esc(q.why)}</h3><p>${ok?'你選對了。再確認一次：正確不是因為「讀起來順」，而是因為它符合上面的結構判斷。':'你選擇的形式與本題要求不一致。對照正確答案，重點檢查助動詞、詞類、時態或固定搭配是否被重複或遺漏。'}</p></section>${related?`<section class="explain-block"><span>回到文法重點</span><h3>${esc(related.title.replace(/^\d+\.\s*/,''))}</h3><p>${esc(related.intro)}</p></section>`:''}<section class="explain-warning"><b>易錯提醒</b><p>${esc(g.pitfall)}</p></section>${mini(chapter,q)}`)}
 return{knowledge,question,close};
})();
