const Explain=(()=>{
 const guides=[
  {match:/时|过去|现在|将来|完成|进行|used to|经历|持续/,name:'时态判断',steps:['先圈出时间词或上下文时间点。','判断动作是习惯、进行过程、完成结果还是已结束事件。','再按主语选择助动词或动词形式。'],pitfall:'不要只靠单个“标志词”机械选择时态；先确认动作与时间参照点的关系。'},
  {match:/疑问|do|does|did|简短回答|否定|语序/,name:'疑问与否定',steps:['先找原句的完整谓语。','已有 be、情态动词或完成时 have 时直接移动它；否则一般时态使用 do。','出现 does 或 did 后，把主要动词恢复原形。'],pitfall:'最常见错误是重复标记：Does she works 和 Did he went 都把时态标记了两次。'},
  {match:/be|there be|have got/,name:'be 与基础结构',steps:['确认表达的是身份、状态、位置、存在还是拥有。','根据主语和时间选择 am/is/are/was/were 或 have/has。','否定和提问时保持同一套结构，不混用 do 与 have got。'],pitfall:'be 句不使用 do 提问；普通 have 与 have got 的提问方式不要混合。'},
  {match:/名词|冠词|可数|不可数|复数|数量|限定|所有格|零冠词/,name:'名词与限定词',steps:['先判断名词是可数还是不可数。','如果是单数可数名词，检查前面是否有限定词。','再根据泛指、特指和数量选择冠词或数量词。'],pitfall:'information、advice、furniture 等常见词在英语中不可数，不能直接加 a 或复数 -s。'},
  {match:/代词|主格|宾格|物主|反身|指示|its|whose/,name:'代词与指代',steps:['先判断这个位置需要主语、宾语还是所属关系。','查看后面是否还有名词：有名词用 my/your 等，没有名词用 mine/yours 等。','确认代词与所指对象在人称和单复数上一致。'],pitfall:'my 后必须接名词；mine 后不能再接名词。its 是“它的”，it’s 是 it is/has。'},
  {match:/形容词|副词|比较|最高|ing-ed|系动词|词性/,name:'修饰与词性',steps:['先找被修饰的词。','修饰名词或放在系动词后通常用形容词；修饰动作通常用副词。','比较时确认是两者比较还是范围内最高。'],pitfall:'-ed 常描述感受者，-ing 常描述引发感受的事物；但判断仍要结合句意。'},
  {match:/介词|地点|方向|距离|时间介词|零介词/,name:'介词关系',steps:['判断表达的是时间、静态位置还是移动方向。','时间从“点—具体日—较长范围”判断 at/on/in。','空间从“点—表面—内部”判断 at/on/in，移动时再看 into/across/through。'],pitfall:'last、next、this、every 前通常不再添加时间介词。'},
  {match:/情态|建议|许可|能力|义务|禁止|不必|推测|祈使/,name:'情态与功能表达',steps:['先判断说话人的目的：能力、许可、建议、义务还是推测。','选择语气强度合适的情态动词。','情态动词后使用动词原形。'],pitfall:'mustn’t 表示禁止，don’t have to 表示没有必要，两者意义不同。'},
  {match:/不定式|动名词|doing|to do|目的|意义差异/,name:'非谓语形式',steps:['查看前面的动词或介词决定基本搭配。','介词后通常使用 doing；want/plan/decide 等常接 to do。','遇到 stop、remember、try 时检查形式变化是否改变意义。'],pitfall:'不要只记“某词后接 doing/to do”，还要把会改变意义的搭配连同例句一起记。'},
  {match:/被动|语态|过去分词|主动转被动/,name:'被动语态',steps:['先确认主语是动作执行者还是承受者。','按时态选择 be 的形式。','主要动词改为过去分词；需要时再用 by 引出执行者。'],pitfall:'be 负责时态，过去分词负责被动，二者缺一不可。'},
  {match:/从句|连词|条件|原因|结果|让步|时间从句|who|that|where|if-whether|关系词/,name:'从句与连接',steps:['先判断两个信息之间的逻辑关系。','选择连接词并确认从句缺少什么成分。','检查从句语序；间接疑问句使用陈述语序。'],pitfall:'避免 because...so 和 although...but 双重连接；if/when 的真实将来从句中通常不用 will。'},
  {match:/主语|谓语|宾语|表语|宾补|双宾语|基本句型|完整句|词性/,name:'句子成分',steps:['先找承担时态的完整谓语。','谓语前通常是主语。','再根据动词类型判断后面是宾语、表语还是补足语。'],pitfall:'宾语补足语描述或命名宾语；双宾语分别表示“给谁”和“给什么”。'}
 ];
 const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const guideFor=tag=>guides.find(g=>g.match.test(tag))||{name:'结构判断',steps:['找出句子的主语和完整谓语。','观察题目要求与上下文线索。','用核心规则逐项排除不符合结构或意义的选项。'],pitfall:'不要只凭中文逐词对应；英语形式由句子位置、时态和搭配共同决定。'};
 function layer(){let el=document.querySelector('#explain-layer');if(!el){el=document.createElement('div');el.id='explain-layer';el.className='explain-layer';el.innerHTML='<button class="explain-backdrop" aria-label="关闭精讲"></button><aside class="explain-sheet" role="dialog" aria-modal="true" aria-labelledby="explain-title"><button class="explain-close" aria-label="关闭">×</button><div id="explain-body"></div></aside>';document.body.appendChild(el);el.querySelector('.explain-backdrop').onclick=close;el.querySelector('.explain-close').onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape')close()})}return el}
 function open(html){const el=layer();el.querySelector('#explain-body').innerHTML=html;el.classList.add('open');document.body.classList.add('no-scroll');el.querySelector('.explain-close').focus();el.querySelectorAll('[data-reveal]').forEach(b=>b.onclick=()=>{const a=b.nextElementSibling;a.hidden=false;b.hidden=true})}
 function close(){document.querySelector('#explain-layer')?.classList.remove('open');document.body.classList.remove('no-scroll')}
 function mini(chapter,current){const q=chapter.qs.find(x=>x.text!==current?.text&&(x.tag===current?.tag||!current))||chapter.qs.find(x=>x.text!==current?.text);if(!q)return'';return `<section class="explain-block mini-check"><span>举一反三</span><h3>${esc(q.text)}</h3><div class="mini-options">${q.options.map((o,i)=>`<i>${String.fromCharCode(65+i)}. ${esc(o)}</i>`).join('')}</div><button class="reveal-btn" data-reveal>查看答案</button><div class="reveal-answer" hidden><b>${String.fromCharCode(65+q.a)}. ${esc(q.options[q.a])}</b><p>${esc(q.why)}</p></div></section>`}
 function knowledge(chapter,index){const s=chapter.sections[index],tag=s.title+' '+s.points.join(' '),g=guideFor(tag);open(`<div class="explain-kicker">KNOWLEDGE DEEP DIVE</div><h2 id="explain-title">${esc(s.title.replace(/^\d+\.\s*/,''))}</h2><p class="explain-lead">${esc(s.intro)}</p><section class="explain-block"><span>一步一步判断</span><ol>${s.points.map(p=>`<li>${esc(p)}</li>`).join('')}</ol></section><section class="explain-block"><span>例句拆解</span>${s.examples.map(e=>`<div class="explain-example"><b>${esc(e[0])}</b><p>${esc(e[1])}</p></div>`).join('')}</section><section class="explain-warning"><b>常见误区</b><p>${esc(s.note||g.pitfall)}</p></section>${mini(chapter)}`)}
 function question(chapter,q,chosen){const g=guideFor(q.tag),selected=Number.isInteger(chosen)?q.options[chosen]:'未作答',ok=chosen===q.a;const related=chapter.sections?.find(s=>(s.title+' '+s.points.join(' ')).includes(q.tag.replace(/时$|句$|式$/g,'')))||chapter.sections?.[0];open(`<div class="explain-kicker">QUESTION DEEP DIVE · ${esc(q.tag)}</div><h2 id="explain-title">这道题怎样一步步判断？</h2><div class="explain-question"><p>${esc(q.text)}</p><div><span class="${ok?'is-correct':'is-wrong'}">你的答案：${esc(selected)}</span><span class="is-correct">正确答案：${esc(q.options[q.a])}</span></div></div><section class="explain-block"><span>${esc(g.name)} · 判断路径</span><ol>${g.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol></section><section class="explain-block"><span>本题落点</span><h3>${esc(q.why)}</h3><p>${ok?'你选对了。再确认一次：正确不是因为“读起来顺”，而是因为它符合上面的结构判断。':'你选择的形式与本题要求不一致。对照正确答案，重点检查助动词、词性、时态或固定搭配是否被重复或遗漏。'}</p></section>${related?`<section class="explain-block"><span>回到知识点</span><h3>${esc(related.title.replace(/^\d+\.\s*/,''))}</h3><p>${esc(related.intro)}</p></section>`:''}<section class="explain-warning"><b>易错提醒</b><p>${esc(g.pitfall)}</p></section>${mini(chapter,q)}`)}
 return{knowledge,question,close};
})();
